// 실습 가이드 문구와 실행할 예시 질문입니다. 새로운 수업 단계를 여기에 추가하세요.
export const GUIDE_STEPS = [
  {
    number: "01",
    title: "챗봇의 이름을 바꿔보세요",
    file: "lib/chat-config.js",
    text: "name과 greeting을 바꾸면 나만의 이름과 첫 인사로 화면이 달라져요.",
    code: 'name: "옥천 식당 도우미",\ngreeting: "옥천의 어떤 식당이 궁금하세요?",',
  },
  {
    number: "02",
    title: "AI에게 역할을 알려주세요",
    file: "lib/ai-config.js",
    text: "SYSTEM_PROMPT는 AI의 역할 설명서예요. 식당 정보는 CSV에 있는 사실만 사용하고, 모르는 것은 모른다고 답하게 해보세요.",
    code: "CSV에 나온 업소명과 주소를 정확하게 안내하세요.\n메뉴와 영업시간은 CSV에 없으므로 추측하지 마세요.",
  },
  {
    number: "03",
    title: "화면에 나만의 색을 입혀보세요",
    file: "app/globals.css",
    text: "--accent 색상을 바꾸고 저장해 보세요. 화면으로 돌아와 버튼과 강조 색상이 어떻게 달라지는지 확인하세요.",
    code: "/* 나만의 테마 색상 */\n--accent: #54765b;",
  },
  {
    number: "04",
    title: "옥천 식당 CSV를 살펴보세요",
    file: "okcheon_restaurant.csv",
    text: "CSV는 쉼표로 칸을 나누는 표예요. 연번, 업종명, 업소명, 도로명 주소, 데이터 기준일의 다섯 컬럼을 확인하세요. 원본에는 메뉴와 영업시간이 없어요.",
    code: "연번,업종명,업소명,소재지(도로명),데이터기준일\n3,일반음식점,풍미당,충청북도 옥천군 옥천읍 중앙로 23-1,2026-09-16",
  },
  {
    number: "05",
    title: "서버에서 CSV를 읽어보세요",
    file: "lib/restaurants.js",
    text: "readFile로 파일을 읽고 parse로 JavaScript 데이터로 바꿔요. split(',')만 쓰면 따옴표 안의 쉼표나 줄바꿈을 잘못 나눌 수 있어 CSV 라이브러리를 사용해요.",
    code: 'const csv = await readFile("okcheon_restaurant.csv", "utf8");\nconst rows = parse(csv, {\n  bom: true, columns: true, skip_empty_lines: true\n});',
  },
  {
    number: "06",
    title: "질문에 맞는 식당을 찾아보세요",
    file: "lib/restaurants.js",
    text: "옥천읍·청산면 같은 지역, 업소 이름, 업종으로 관련 행을 찾아요. 한 번에 최대 12곳만 AI에 보내고, 전체 검색 건수는 따로 알려줘요. 카페는 이름에 카페·커피 등이 들어간 후보를 찾아요.",
    code: "const result = searchRestaurants(restaurants, messages);\n// result.sources: 선택한 업소\n// result.info.matched: 전체 검색 건수",
    prompts: [
      "옥천읍에 어떤 식당이 있는지 5곳 알려줘.",
      "청산면에 등록된 업소는 몇 개야?",
    ],
  },
  {
    number: "07",
    title: "검색한 자료를 AI에게 건네주세요",
    file: "app/api/chat/route.js",
    text: "AI는 내 파일을 스스로 열 수 없어요. 서버가 관련 데이터를 찾아 역할 설명과 함께 보내야 해요. 이것이 검색한 자료를 참고해 답하는 챗봇의 기본 흐름이에요.",
    code: 'messages: [\n  { role: "system",\n    content: SYSTEM_PROMPT + restaurantContext(result) },\n  ...messages\n],\nstream: true',
  },
  {
    number: "08",
    title: "답변과 원본 데이터를 비교해보세요",
    file: "components/chat.js",
    text: "질문을 눌러 대화해보고 답변 아래의 ‘참고한 CSV 자료’를 펼쳐보세요. AI가 말한 업소명과 주소가 원본과 같은지 확인해요. 결과는 실시간으로 스트리밍돼요.",
    code: "질문: 풍미당 주소 알려줘.\n원본: 충청북도 옥천군 옥천읍 중앙로 23-1\n확인: 답변과 CSV의 주소가 같은가요?",
    prompts: [
      "풍미당 주소 알려줘.",
      "옥천읍에 이름에 카페나 커피가 들어간 업소 3곳 알려줘.",
    ],
  },
  {
    number: "09",
    title: "데이터에 없는 정보도 질문해보세요",
    file: "lib/ai-config.js",
    text: "영업시간·메뉴·가격·별점은 원본에 없어요. AI가 모른다고 말하는지 확인하세요. 가게 이름만 보고 메뉴를 단정하지 않고, 실제 방문 전에는 최신 정보를 직접 확인해요.",
    code: "CSV에 없는 항목: 메뉴, 영업시간, 가격, 전화번호, 별점\n검색 결과가 0개: 다른 조건으로 다시 질문하기",
    prompts: [
      "풍미당의 영업시간과 메뉴 가격 알려줘.",
      "옥천 우주정거장식당 주소 알려줘.",
    ],
  },
  {
    number: "10",
    title: "데이터를 바꾸고 다시 배포해보세요",
    file: "next.config.mjs",
    text: "CSV의 행을 추가하거나 주소를 수정한 뒤 같은 질문으로 비교해보세요. 연번은 중복 없이, 다섯 컬럼은 그대로 유지하세요. GitHub에는 CSV도 함께 올리고 Vercel을 다시 배포해야 반영돼요. 이 설정은 서버 함수에 CSV를 포함해요.",
    code: 'outputFileTracingIncludes: {\n  "/api/chat": ["./okcheon_restaurant.csv"]\n}',
  },
];
